name: Verify and Apply Peribolos
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  project:
    name: Apply peribolos.yaml to the org
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
